#!/bin/sh
. "$(dirname "$0")/husky.sh"

echo "Pre-commit hook is running..."
pwd echo "kmlnlnk $PWD"
# Build the client
echo "Building the client..."
if [  "client" ]; then
   
    npm run build
    BUILD_STATUS=$?
    cd ..
else
    echo "Client directory not found!"
    exit 1
fi

if [ $BUILD_STATUS -ne 0 ]; then
    echo "Client build failed! Commit aborted."
    exit 1
else
    echo "Client built successfully."
fi

echo "Client build succeeded. Proceeding with the commit."
