import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { getServerSession } from "next-auth";
import SessionProvider  from "@/components/layouts/other/sessionprovider";
import Sidebar from "@/components/layouts/dashbord/Sidebar-employer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recruitwise",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session} >
        {children}
        </SessionProvider>
        </body>
    </html>
  );
}
