export const jobTitles = [
    "Software Engineer",
    "Data Scientist",
    "Product Manager",
    "Designer",
    "Marketing Specialist",
    "Sales Representative",
    "Chief Executive Officer (CEO)",
    "Chief Operating Officer (COO)",
    "Chief Financial Officer (CFO)", // Ensure this key is unique
    "Managing Director",
    "Operations Manager",
    "Project Manager",
    "Business Analyst",
    "Product Manager",
    "Brand Manager",
    "Business Development Manager",
    "Account Manager",
    "Sales Manager",
    "Human Resources Manager",
    "Customer Service Manager",
    "Technology & IT",
    "Software Engineer/Developer",
    "Web Developer",
    "Full Stack Developer",
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "DevOps Engineer",
    "Cloud Architect",
    "System Administrator",
    "IT Support Specialist",
    "Cybersecurity Analyst",
    "Database Administrator",
    "UI/UX Designer",
    "Frontend Developer",
    "Backend Developer",
    "Marketing & Sales",
    "Marketing Manager",
    "Content Marketing Manager",
    "Digital Marketing Specialist",
    "SEO Specialist",
    "Social Media Manager",
    "Brand Strategist",
    "Sales Representative",
    "Sales Director",
    "Account Executive",
    "Customer Success Manager",
    "Public Relations Manager",
    "Advertising Manager",
    "Finance & Accounting",
    "Accountant",
    "Financial Analyst",
    "Auditor",
    "Tax Manager",
    "Investment Banker",
    "Controller",
    "Treasury Analyst",
    "Credit Analyst",
    "Budget Analyst",
    "Actuary",
    "Healthcare & Medical",
    "Doctor/Physician",
    "Nurse",
    "Medical Assistant",
    "Pharmacist",
    "Physical Therapist",
    "Occupational Therapist",
    "Healthcare Administrator",
    "Dentist",
    "Medical Laboratory Technician",
    "Radiologic Technologist",
    "Clinical Research Coordinator",
    "Psychiatrist",
    "Surgeon",
    "Legal",
    "Lawyer/Attorney",
    "Paralegal",
    "Legal Assistant",
    "Corporate Counsel",
    "Judge",
    "Legal Consultant",
    "Legal Secretary",
    "Contract Manager",
    "Education & Training",
    "Teacher",
    "Professor",
    "Educational Coordinator",
    "School Principal",
    "Instructional Designer",
    "Curriculum Developer",
    "Librarian",
    "Tutor",
    "Education Consultant",
    "Creative & Design",
    "Graphic Designer",
    "Art Director",
    "Content Writer",
    "Copywriter",
    "Video Editor",
    "Animator",
    "Photographer",
    "Creative Director",
    "Illustrator",
    "Fashion Designer",
    "Interior Designer",
    "User Experience (UX) Designer",
    "Manufacturing & Engineering",
    "Mechanical Engineer",
    "Civil Engineer",
    "Electrical Engineer",
    "Quality Assurance Specialist",
    "Manufacturing Manager",
    "Production Supervisor",
    "Industrial Engineer",
    "Supply Chain Manager",
    "Maintenance Technician",
    "Construction Manager",
    "Human Resources",
    "HR Manager",
    "HR Specialist",
    "Recruiter",
    "Talent Acquisition Manager",
    "Compensation and Benefits Manager",
    "Employee Relations Specialist",
    "HR Coordinator",
    "Learning and Development Specialist",
    "Retail & Hospitality",
    "Store Manager",
    "Sales Associate",
    "Customer Service Representative",
    "Hotel Manager",
    "Event Planner",
    "Restaurant Manager",
    "Bartender",
    "Chef",
    "Concierge",
    "Housekeeping Manager",
    "Logistics & Transportation",
    "Logistics Coordinator",
    "Supply Chain Manager",
    "Warehouse Manager",
    "Truck Driver",
    "Logistics Analyst",
    "Fleet Manager",
    "Transportation Planner",
    "Air Traffic Controller",
    "Delivery Driver",
    "Science & Research",
    "Research Scientist",
    "Laboratory Technician",
    "Biologist",
    "Chemist",
    "Pharmacologist",
    "Environmental Scientist",
    "Research Analyst",
    "Clinical Research Associate"
  ];
      