export const jobTitles = [
  "Account Executive",
  "Account Manager",
  "Accountant",
  "Actuary",
  "Advertising Manager",
  "Air Traffic Controller",
  "Animator",
  "Auditor",
  "Backend Developer",
  "Biologist",
  "Brand Manager",
  "Brand Strategist",
  "Business Analyst",
  "Business Development Manager",
  "Chef",
  "Chief Executive Officer (CEO)",
  "Chief Financial Officer (CFO)",
  "Chief Operating Officer (COO)",
  "Clinical Research Associate",
  "Clinical Research Coordinator",
  "Cloud Architect",
  "Compensation and Benefits Manager",
  "Contract Manager",
  "Construction Manager",
  "Content Marketing Manager",
  "Content Writer",
  "Copywriter",
  "Creative Director",
  "Creative & Design",
  "Cybersecurity Analyst",
  "Customer Service Manager",
  "Customer Service Representative",
  "Customer Success Manager",
  "Data Analyst",
  "Data Scientist",
  "Database Administrator",
  "Dentist",
  "Delivery Driver",
  "Digital Marketing Specialist",
  "Doctor/Physician",
  "Education Consultant",
  "Educational Coordinator",
  "Electrical Engineer",
  "Employee Relations Specialist",
  "Event Planner",
  "Fashion Designer",
  "Finance & Accounting",
  "Fleet Manager",
  "Financial Analyst",
  "Graphic Designer",
  "Healthcare & Medical",
  "Healthcare Administrator",
  "Hotel Manager",
  "Human Resources",
  "HR Coordinator",
  "HR Manager",
  "HR Specialist",
  "Industrial Engineer",
  "Instructional Designer",
  "Investment Banker",
  "Illustrator",
  "IT Support Specialist",
  "Judge",
  "Laboratory Technician",
  "Lawyer/Attorney",
  "Learning and Development Specialist",
  "Legal",
  "Legal Assistant",
  "Legal Consultant",
  "Legal Secretary",
  "Logistics Analyst",
  "Logistics Coordinator",
  "Logistics & Transportation",
  "Machine Learning Engineer",
  "Maintenance Technician",
  "Manager",
  "Managing Director",
  "Marketing & Sales",
  "Marketing Manager",
  "Marketing Specialist",
  "Mechanical Engineer",
  "Medical Assistant",
  "Medical Laboratory Technician",
  "Nurse",
  "Operations Manager",
  "Paralegal",
  "Pharmacist",
  "Physical Therapist",
  "Photographer",
  "Product Manager",
  "Project Manager",
  "Public Relations Manager",
  "Quality Assurance Specialist",
  "Radio Technologist",
  "Recruiter",
  "Research Analyst",
  "Research Scientist",
  "Retail & Hospitality",
  "Sales Director",
  "Sales Manager",
  "Sales Representative",
  "School Principal",
  "Software Engineer",
  "Software Engineer",
  "Software FontEnd Developer",
  "Software BackEnd Developer",
  "System Administrator",
  "Social Media Manager",
  "Supply Chain Manager",
  "Surgeon",
  "Tax Manager",
  "Teacher",
  "Technology & IT",
  "Telecom Engineer",
  "Transportation Planner",
  "Treasury Analyst",
  "Truck Driver",
  "UI/UX Designer",
  "User Experience (UX) Designer",
  "Warehouse Manager",
  "Web Developer",
  "Judge",
  "Writer",
];
