apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: skillmatch
spec:
rules:
  - host: www.yourdomain.com 
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: skillmatch.azurecr.io/client
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SERVER_URL
              value: "http://api-gateway-service.skillmatch.svc.cluster.local:3001"
      imagePullSecrets:
        - name: acr-secret  # Correct placement of imagePullSecrets

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: skillmatch
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
