#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-push hook"


cd client || { echo "Client directory not found!" >&2; exit 1; }
echo "in client directory"
npm run build
echo "Changed to client directory"

# Check if the build command was successful
if [ $? -eq 0 ]; then
    echo "Build successful! pushing to remote"
    exit 0  # Exit with success
else
    echo "Build failed!" >&2
    exit 1  # Exit with failure
fi
